### PR TITLE
feat: Remove price-database

### PR DESCRIPTION
**Pull request by olerichter00**
Addresses [CX-3601]

## Description

Remove price-database.

[CX-3601]: https://artsyproduct.atlassian.net/browse/CX-3601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by MounirDhahri — APPROVED** [review]
Niiiice

**Comment by MounirDhahri** [comment]
Let's get this to Force 🚀 (and wwwify)

**Comment by MounirDhahri** [comment]
probably not since we do auto updates  👀

**Comment by artsyit** [comment]
:rocket: PR was released in [`v1.6.0`](https://github.com/artsy/artsy-eigen-web-association/releases/tag/v1.6.0) :rocket:

**Pull request merged**
