### PR TITLE
prevent collection pages from opening in the app

### PR DESCRIPTION
**Pull request by xtina-starr**
Addresses: https://artsyproduct.atlassian.net/browse/GROW-996

This PR adds the collection paths (`/collection/:id`) to the `apple-app-site-association.json` to be blacklisted so that they won't show up in the iOS app. It seems pretty straightforward but I'm wondering how do I go about verifying this. That's why I've marked this as WIP because it's not yet be verified.

### CODE REVIEW

**Comment by alloy** [comment]
To make sure these links get excluded when sent through Sailthru as well you should run this script: https://github.com/artsy/artsy-eigen-web-association/blob/master/add-sailthru-paths.js

```
$ node add-sailthru-paths.js
```

Once this is merged and updated in Force, artsy-wwwify, and uploaded to Sailthru, you should be able to verify this in the app (you may need to reboot your device).

**Comment by alloy** [comment]
Can you also add these steps I listed to the README?

**Comment by xtina-starr** [comment]
So instruction for running the script are actually in the README under [Change config file](https://github.com/artsy/artsy-eigen-web-association#changing-config-file). It's handled in the `yarn build` command. I did fix one minor error in the script comments though.

**Comment by alloy** [comment]
Ping me when/if this needs another review.

**Comment by xtina-starr** [comment]
Had a sync up with product and it seems we want to move forward with this approach so another review would be awesome.

**Comment by alloy** [comment]
Sorry, I missed your question. Is this still the case?

**Comment by artsyit** [comment]
:rocket: PR was released in [`v1.1.0`](https://github.com/artsy/artsy-eigen-web-association/releases/tag/v1.1.0) :rocket:

**Pull request merged**
