### PR TITLE
@alloy => Restricts all articles from going to the app

### PR DESCRIPTION
**Pull request by kanaabe**
Was asked to restrict all articles opened from links on mobile from opening in the app. 

cc @owendodd

### CODE REVIEW

**Comment by alloy** [comment]
The change looks good, I'm just wondering why this is and if/where previous discussion about this took place?

**Comment by kanaabe** [comment]
Good question! I wasn't at today's Content meeting but it was discussed then, and I believe Carter brought it up. That's as much as I know! 

I think it has to do with speed (currently have to wait for the app to load, and then open a web page as opposed to getting to the content asap), but don't quote me on that. 

@owendodd could you provide more context?

**Comment by alloy** [comment]
Yeah that makes sense and it's not like the app offers much over a browser when it comes to articles, except showing linked artists/artworks in their native Eigen views.

**Comment by owendodd** [comment]
Yeah Kana highlighted most of the important points. 

It's mostly a speed issue. Editorial content definitely _feels_ slower when opening in app vs browser. Increasing engagement there feels like a big win, especially from email.  

It's something we have talked about a few times before and just never gotten around to doing.

**Comment by alloy** [comment]
Thanks for the info 🙏🏽

**Comment by kanaabe** [comment]
@alloy is there any reason this wouldn't work for some situations? I'm trying to replicate what Carter reported -- he clicked from a Hacker News post to an Artsy link and it opened up the app. I've tried with different browsers but it doesn't bring me to the app.

**Comment by alloy** [comment]
@kanaabe Hrmm, not from the top of my head. What was the URL?

**Comment by kanaabe** [comment]
https://www.artsy.net/article/artsy-editorial-break-artwork

**Comment by alloy** [comment]
Yup, opens with the app for me too. How are you trying to get reproduce this? (It is only triggered if you tap a link, not if you enter it in e.g. a browser’s address bar.)

The reason is that it appears these changes were not deployed to Force and the www-ify app, looking at `www.artsy.net` and `artsy.net` shows that neither include the exclusion patterns: https://limitless-sierra-4673.herokuapp.com. And indeed [the signed file](https://github.com/artsy/artsy-eigen-web-association/blob/master/apple-app-site-association) was not updated in this PR, so I should have realised then that it wasn’t going to be deployed, my bad.

Let me know if the instructions in the README work for you and afterwards be sure to update this dependency in the apps.

**Comment by kanaabe** [comment]
Ah interesting -- thanks for the explanation. My bad for not reading the docs beforehand. As for reproducing, I'm tapping the link normally so _that_ is still a mystery.

**Comment by artsyit** [comment]
:rocket: PR was released in [`v1.1.0`](https://github.com/artsy/artsy-eigen-web-association/releases/tag/v1.1.0) :rocket:

**Pull request merged**
